# Generated by Django 4.1.1 on 2022-09-28 19:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
