# Generated by Django 4.1.1 on 2022-09-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_izoh_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izoh',
            name='video',
        ),
    ]
